[project]
name = "buch-generativekimitpython-auflage2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "accelerate>=1.14.0",
    "agent-framework-core>=1.13.0",
    "agent-framework-openai>=1.12.0",
    "agent-framework-orchestrations>=1.0.2",
    "agentops>=0.4.21",
    "datasets>=5.0.1",
    "diffusers>=0.39.0",
    "fastapi>=0.141.1",
    "ipykernel>=7.3.0",
    "langchain>=1.3.14",
    "langchain-arxiv>=0.1.0",
    "langchain-arxiv-retriever>=1.0.0",
    "langchain-chroma>=1.1.0",
    "langchain-classic>=1.0.8",
    "langchain-community>=0.4.2",
    "langchain-experimental>=0.4.2",
    "langchain-faiss>=0.1.1",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.4.1",
    "langchain-openrouter>=0.2.7",
    "langchain-pinecone>=0.2.13",
    "langchain-tavily>=0.2.18",
    "langchain-text-splitters>=1.1.2",
    "logfire[system-metrics]>=4.40.0",
    "matplotlib>=3.11.1",
    "mcp[cli]>=2.0.0",
    "openai>=2.52.0",
    "pandas>=3.0.5",
    "pyperclip>=1.11.0",
    "python-dotenv>=1.2.2",
    "rank-bm25>=0.2.2",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.7.0",
    "sentencepiece>=0.2.2",
    "streamlit>=1.61.1",
    "torch>=2.13.0",
    "transformers>=5.14.1",
    "uvicorn>=0.52.0",
    "wikipedia>=1.4.0",
]
